version: '3.1'

services:

  mongo:
    image: mongo:4.2.11-bionic
    restart: always
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
